apiVersion: v1
kind: Service
metadata:
  name: {{ template "svn.fullname" . }}
  labels:
{{- if .Values.subversion.labels }}
{{ toYaml .Values.subversion.labels | indent 4 }}
{{- end }}
spec:
  ports:
    - name: http-admin
      {{- if eq .Values.subversion.service.type "NodePort" }}
      nodePort: {{ .Values.subversion.service.nodeProts.http }}
      {{- end }}
      port: 3343
      protocol: TCP
      targetPort: 3343
    - name: https-admin
      {{- if eq .Values.subversion.service.type "NodePort" }}
      nodePort: {{ .Values.subversion.service.nodeProts.https }}
      {{- end }}
      port: 4434
      protocol: TCP
      targetPort: 4434
    - name: http-svn
      {{- if eq .Values.subversion.service.type "NodePort" }}
      nodePort: {{ .Values.subversion.service.nodeProts.svn }}
      {{- end }}
      port: 18080
      protocol: TCP
      targetPort: 18080
  selector:
    app: subversion-edge
    release: svn
  type: {{ .Values.subversion.service.type }}
